use crate::db::values::{Timestamp, TransactionType, UID};

entity!(
    /// A description of a transaction.
    pub struct Transaction in Transactions {
        /// The unique identifier.
        ///
        /// We want these to be generated by the database, so we use a plain
        /// integer.
        uid: i64,

        /// The type of transaction.
        transaction_type: TransactionType,

        /// The user involved in this transaction.
        user_uid: UID,

        /// A description.
        description: String,

        /// The amount.
        amount: i64,

        /// The timestamp of this transaction.
        time: Timestamp,
    }
);

entity_tests! {
    Transaction[i64 = i64::default()] {
        entity: |id| Transaction {
            uid: id,
            transaction_type: TransactionType::Gift,
            user_uid: UID::new(),
            description: "description".into(),
            amount: 42,
            time: Timestamp::now(),
        };
        modify: |e| Transaction {
            description: "another description".into(),
            ..e
        };
        prepare: |c, e| {
            let u = crate::db::entities::user::tests::entity_with_id(
                e.user_uid().clone(),
            );
            crate::db::entities::user::tests::prepare(c, &u).await?;
            u.create(c).await
        };
    }
}
